In [ ]:
import torch

In [ ]:
ran = torch.rand(5,5, dtype=torch.float64)
d = ran @ ran.T + 1e-5

In [ ]:
d

tensor([[2.1157, 1.6960, 1.3807, 2.0091, 1.2477],
        [1.6960, 1.5403, 1.4525, 1.9626, 1.0250],
        [1.3807, 1.4525, 1.6791, 2.0742, 1.0316],
        [2.0091, 1.9626, 2.0742, 2.8813, 1.6865],
        [1.2477, 1.0250, 1.0316, 1.6865, 1.5130]], dtype=torch.float64)

In [ ]:
a = torch.rand(5,5, dtype=torch.float64)

In [ ]:
Q = torch.linalg.qr(a).Q

In [ ]:
Q @ d @ Q.T

tensor([[ 0.9317, -1.4794,  0.9637, -1.2813, -0.1782],
        [-1.4794,  4.6029, -1.9401,  3.0748,  0.7384],
        [ 0.9637, -1.9401,  1.2851, -1.4728, -0.4926],
        [-1.2813,  3.0748, -1.4728,  2.2845,  0.3230],
        [-0.1782,  0.7384, -0.4926,  0.3230,  0.6251]], dtype=torch.float64)

In [ ]:
A = torch.rand(3,3)

In [ ]:
Q,R = torch.linalg.qr(A)

In [ ]:
Q, R

(tensor([[-0.5216,  0.0729, -0.8501],
         [-0.7627, -0.4865,  0.4262],
         [-0.3825,  0.8706,  0.3093]]),
 tensor([[-1.1534, -0.7000, -0.7603],
         [ 0.0000,  0.7366,  0.2398],
         [ 0.0000,  0.0000, -0.3977]]))

In [ ]:
Q.T @ Q

tensor([[ 1.0000e+00,  0.0000e+00, -2.9802e-08],
        [ 0.0000e+00,  1.0000e+00, -5.9605e-08],
        [-2.9802e-08, -5.9605e-08,  1.0000e+00]])

Cho solve

In [ ]:
from meteo_imp.gaussian import to_posdef

In [ ]:
A = to_posdef(torch.rand(3,3))
B = torch.rand(3,3)

In [ ]:
x = torch.inverse(A) @ B
x

tensor([[ 31.5294,   4.7335,  51.6443],
        [  1.4137,   1.7132,   3.0639],
        [-18.4855,  -3.2360, -31.1095]])

In [ ]:
C = torch.linalg.cholesky(A)

In [ ]:
torch.cholesky_solve(B, C)

tensor([[ 31.5293,   4.7335,  51.6443],
        [  1.4136,   1.7132,   3.0639],
        [-18.4855,  -3.2360, -31.1094]])

In [ ]:
torch.linalg.qr

In [ ]:
A = torch.randn(3, 3, requires_grad=True)

In [ ]:
A = A @ A.mT

In [ ]:
LD, pivots = torch.linalg.ldl_factor(A)

In [ ]:
LD.sum().backward()

RuntimeError: derivative for aten::linalg_ldl_factor_ex is not implemented