# PCA

exploration of PCA for init parameters

In [ ]:
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
t0 = np.random.randn(5,1) * 10
tt = np.hstack([t0, 2 * t0 + np.random.randn(5,1), 3 * t0 + np.random.randn(5,1)])

In [ ]:
tt = np.vstack([tt, -tt])

In [ ]:
tt.mean(0)

array([-8.88178420e-17,  0.00000000e+00, -1.59872116e-15])

In [ ]:
def pca(X):
    # Data matrix X, assumes 0-centered
    n, m = X.shape
    assert np.allclose(X.mean(axis=0), np.zeros(m))
    # Compute covariance matrix
    C = np.dot(X.T, X) / (n-1)
    # Eigen decomposition
    eigen_vals, eigen_vecs = np.linalg.eig(C)
    # Project X onto PC space
    X_pca = np.dot(X, eigen_vecs)
    return X_pca, eigen_vecs

In [ ]:
pca(tt)

(array([[ 4.86387982e+00, -1.41975358e-02,  1.92176031e+00],
        [ 3.60233996e+01,  2.33725703e-01, -4.02597844e-01],
        [ 3.09057872e+01, -3.14141537e-01,  1.15917989e+00],
        [ 1.60022488e+01,  3.52349936e-01,  3.35200954e-01],
        [ 2.04880798e+01, -2.08908751e-01, -1.75875946e+00],
        [-4.86387982e+00,  1.41975358e-02, -1.92176031e+00],
        [-3.60233996e+01, -2.33725703e-01,  4.02597844e-01],
        [-3.09057872e+01,  3.14141537e-01, -1.15917989e+00],
        [-1.60022488e+01, -3.52349936e-01, -3.35200954e-01],
        [-2.04880798e+01,  2.08908751e-01,  1.75875946e+00]]),
 array([[ 0.26875523,  0.96317815, -0.00764675],
        [ 0.53111826, -0.15481125, -0.83303473],
        [ 0.80354466, -0.21982111,  0.55316784]]))

In [ ]:
sk_pc = PCA(2).fit(tt)

In [ ]:
tt @ sk_pc.components_.T

array([[  4.86387982,   1.92176031],
       [ 36.02339962,  -0.40259784],
       [ 30.9057872 ,   1.15917989],
       [ 16.00224879,   0.33520095],
       [ 20.48807979,  -1.75875946],
       [ -4.86387982,  -1.92176031],
       [-36.02339962,   0.40259784],
       [-30.9057872 ,  -1.15917989],
       [-16.00224879,  -0.33520095],
       [-20.48807979,   1.75875946]])

In [ ]:
tr = sk_pc.transform(tt)
tr

array([[  4.86387982,   1.92176031],
       [ 36.02339962,  -0.40259784],
       [ 30.9057872 ,   1.15917989],
       [ 16.00224879,   0.33520095],
       [ 20.48807979,  -1.75875946],
       [ -4.86387982,  -1.92176031],
       [-36.02339962,   0.40259784],
       [-30.9057872 ,  -1.15917989],
       [-16.00224879,  -0.33520095],
       [-20.48807979,   1.75875946]])

In [ ]:
sk_pc.components_.T

array([[ 0.26875523, -0.00764675],
       [ 0.53111826, -0.83303473],
       [ 0.80354466,  0.55316784]])

In [ ]:
(sk_pc.components_ @ tt.T).T

array([[  4.86387982,   1.92176031],
       [ 36.02339962,  -0.40259784],
       [ 30.9057872 ,   1.15917989],
       [ 16.00224879,   0.33520095],
       [ 20.48807979,  -1.75875946],
       [ -4.86387982,  -1.92176031],
       [-36.02339962,   0.40259784],
       [-30.9057872 ,  -1.15917989],
       [-16.00224879,  -0.33520095],
       [-20.48807979,   1.75875946]])

In [ ]:
tt[0, None]

array([[1.27882313, 0.98460024, 4.97452158]])

In [ ]:
sk_pc.components_.shape

(2, 3)

In [ ]:
tt[0].shape

(3,)

In [ ]:
(sk_pc.components_ @ tt[0])

array([4.86387982, 1.92176031])

In [ ]:
tt[0]

array([1.27882313, 0.98460024, 4.97452158])

In [ ]:
sk_pc.components_.T @ tr[0]

array([1.29249789, 0.9824023 , 4.97140066])

In [ ]:
sk_pc.inverse_transform(tr[0])

array([1.29249789, 0.9824023 , 4.97140066])