## Positive semi-definite

need to be sure that the matrix is a positive semi-definite, so we can use choleshy decomposition where if $A$ is positive semidefinite it can be decomposed as $A=LL^T$ where $L$ is a lower triangular matrix.
Therefore the idea is to have as the raw parameter $L$ which we'll enforce to be a lower triangular matrix

In [ ]:
import torch

In [ ]:
R = torch.rand(3,3, requires_grad=True) 

In [ ]:
L = torch.tril(R)

In [ ]:
L.sum().backward() 

In [ ]:
L

tensor([[0.6097, 0.0000, 0.0000],
        [0.6872, 0.5714, 0.0000],
        [0.6097, 0.9560, 0.4841]], grad_fn=<TrilBackward0>)

In [ ]:
torch.distributions.MultivariateNormal(torch.zeros(3), R @ R.T)

MultivariateNormal(loc: torch.Size([3]), covariance_matrix: torch.Size([3, 3]))

In [ ]:
for i in range(10_000):
    R = torch.rand(3,3)
    cov = R @ R.T + (torch.eye(3) * 1e-7)
    torch.distributions.MultivariateNormal(torch.zeros(3), cov)

In [ ]:
for i in range(10_000):
    R = torch.rand(3,3)
    L = torch.tril(R)
    torch.distributions.MultivariateNormal(torch.zeros(3), L @ L.T)

ValueError: Expected parameter covariance_matrix (Tensor of shape (3, 3)) of distribution MultivariateNormal(loc: torch.Size([3]), covariance_matrix: torch.Size([3, 3])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[0.3166, 0.4638, 0.4075],
        [0.4638, 0.6800, 0.6019],
        [0.4075, 0.6019, 0.5586]])

In [ ]:
from gpytorch.constraints import Positive
import torch

In [ ]:
cov = torch.eye(3)

In [ ]:
constraint = Positive()

In [ ]:
raw = constraint.inverse_transform(cov)
raw

tensor([[0.5413,   -inf,   -inf],
        [  -inf, 0.5413,   -inf],
        [  -inf,   -inf, 0.5413]])

In [ ]:
constraint.transform(raw)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
constraint.inverse_transform(cov + torch.fill(cov, 1e-7))

tensor([[  0.5413, -16.1181, -16.1181],
        [-16.1181,   0.5413, -16.1181],
        [-16.1181, -16.1181,   0.5413]])

In [ ]:
raw2 = -torch.ones(3,3)

In [ ]:
raw2

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [ ]:
constraint.transform(raw2)

tensor([[0.3133, 0.3133, 0.3133],
        [0.3133, 0.3133, 0.3133],
        [0.3133, 0.3133, 0.3133]])

### Symmetric

In [ ]:
from meteo_imp.kalman.filter import *

In [ ]:
import torch

In [ ]:
A = torch.rand(100, 100)

In [ ]:
A.dtype

torch.float32

In [ ]:
symmetric_upto(A * A.T, -10)

-10

In [ ]:
torch.tril(A) * torch.tril(A).T

tensor([[0.0088, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1427, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5120,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.1121, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.3522, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2634]])