# Gaussian Distributions Utils
> tools to work with gaussian distributions

In [ ]:
#| hide
#| default_exp gaussian

In [ ]:
from fastcore.test import *

In [ ]:
import altair as alt

## Normal Parameters

In [ ]:
#| export
from collections import namedtuple
from fastcore.basics import patch

### Normal

In [ ]:
import torch

In [ ]:
#| export
ListNormal = namedtuple('ListNormal', ['mean', 'std'])

In [ ]:
#| export
Normal = namedtuple('Normal', ['mean', 'std'])

In [ ]:
#| export
@patch
def __getitem__(self: ListNormal, n:int
           )->Normal:
    """Get the mean and cov for the nth Normal distribution in the list """
    return Normal(self.mean[n], self.std[n])

In [ ]:
#| export
@patch
def detach(self: ListNormal)->ListNormal:
    """Detach both mean and cov at once """
    return ListNormal(self.mean.detach(), self.std.detach())

In [ ]:
ListNormal(torch.rand(10), torch.rand(10))[1]

Normal(mean=tensor(0.7191), std=tensor(0.3329))

### Multivariate Normal

In [ ]:
#| export
ListMNormal = namedtuple('ListMultiNormal', ['mean', 'cov'])

In [ ]:
#| export
MNormal = namedtuple('MultiNormal', ['mean', 'cov'])

In [ ]:
#| export
@patch
def __getitem__(self: ListMNormal, n:int
           )->Normal:
    """Get the mean and cov for the nth Normal distribution in the list """
    return MNormal(self.mean[n], self.cov[n])
@patch
def __setitem__(self: ListMNormal, idx, value)->Normal:
    """set the mean and cov for the nth Normal distribution in the list """
    self.mean[idx], self.cov[idx] = value

In [ ]:
#| export
@patch
def detach(self: ListMNormal)->ListMNormal:
    """Detach both mean and cov at once """
    return ListMNormal(self.mean.detach(), self.cov.detach())

In [ ]:
ListMNormal(torch.rand(2,10), torch.rand(2,10,10))[1]

MultiNormal(mean=tensor([0.4603, 0.2562, 0.9757, 0.4384, 0.2227, 0.9217, 0.5756, 0.7677, 0.2445,
        0.0505]), cov=tensor([[0.3070, 0.8379, 0.5412, 0.2473, 0.0986, 0.3410, 0.6259, 0.2769, 0.3988,
         0.8348],
        [0.4373, 0.2388, 0.8108, 0.4122, 0.1916, 0.3167, 0.3724, 0.5700, 0.4922,
         0.8885],
        [0.1416, 0.7021, 0.0625, 0.8088, 0.5036, 0.2329, 0.9845, 0.4233, 0.0777,
         0.2951],
        [0.5988, 0.6714, 0.3424, 0.6573, 0.1094, 0.3303, 0.0663, 0.5161, 0.9875,
         0.6968],
        [0.3469, 0.9743, 0.0018, 0.7009, 0.0562, 0.5635, 0.9524, 0.6972, 0.9011,
         0.0044],
        [0.5025, 0.3612, 0.4677, 0.9149, 0.2311, 0.7340, 0.7727, 0.5780, 0.6749,
         0.8674],
        [0.5830, 0.4016, 0.9420, 0.9235, 0.0139, 0.6486, 0.6129, 0.5584, 0.0152,
         0.7531],
        [0.5737, 0.4675, 0.0965, 0.9241, 0.6210, 0.4801, 0.8736, 0.4575, 0.9544,
         0.0306],
        [0.9546, 0.1408, 0.1523, 0.0251, 0.5824, 0.2517, 0.5247, 0.2154, 0.8175,
        

## Positive Definite

The covariance matrices need to be [positive definite](https://en.wikipedia.org/wiki/Definite_matrix)
Those are utilities functions to check is a matrix is positive definite and to make any matrix positive definite

#### Other libraries

Most libraries that implement Kalman Filters use manually specified parameters, which often don't have the issue of the positive definite constraint (eg. `pykalman`)

From `statsmodels` statespace models:
>Cholesky decomposition [...] requires that the matrix be positive definite. While this
          should generally be true, it may not be in every case. [source](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.kalman_filter.KalmanFilter.set_inversion_method.html#statsmodels.tsa.statespace.kalman_filter.KalmanFilter.set_inversion_method)

which seems to mean that they take into account the fact that during the filter calculations may not be positive definite



In [ ]:
#| export
import pandas as pd
from torch import Tensor

In [ ]:
A = torch.rand(2,3,3) # batched random matrix used for testing

#### Symmetry

In [ ]:
#| export
def is_symmetric(value, atol=1e-5):
    return torch.isclose(value, value.mT, atol=atol).all(-1).all(-1)

In [ ]:
is_symmetric(A)

tensor([False, False])

In [ ]:
#| export
def symmetric_upto(value, start=-8):
    for exp in torch.arange(start, 3):
        if is_symmetric(value, atol=10**exp):
            return exp.item()
    return exp.item()

def symmetric_upto_batched(value, start=-8):
    return torch.tensor([symmetric_upto(v) for v in value])

In [ ]:
symmetric_upto_batched(A)

tensor([0, 0])

#### is posdef

Default pytorch check (uses symmetry + cholesky decomposition)

In [ ]:
#| export
def is_posdef(cov):
    return torch.distributions.constraints.positive_definite.check(cov)

In [ ]:
is_posdef(A)

tensor([False, False])

check if it is pos definite using eigenvalues. Positive definite matrix have all positive eigenvalues

In [ ]:
torch.linalg.eigvalsh(A)

tensor([[-0.6106,  0.1669,  1.1203],
        [-0.6198,  0.0409,  1.1183]])

In [ ]:
#| export
def is_posdef_eigv(cov):
    try:
        eigv = torch.linalg.eigvalsh(cov)
        return eigv.ge(0).all(-1), eigv
    except torch._C._LinAlgError:
        return torch.tensor(False), torch.tensor(torch.nan)

In [ ]:
is_posdef_eigv(A)

(tensor([False, False]),
 tensor([[-0.6239,  0.0300,  1.6272],
         [-0.8267,  0.0572,  1.2181]]))

### Pytorch constraint

Note that `is_posdef` and `is_posdef_eigv` can return different values, in general `is_posdef_eigv` is more tollerant

transform any matrix $A$ into a positive definite matrix ($PD$) using the following formula

$PD = AA^T + aI$ 

where $AA^T$ is a positive semi-definite matrix and $a$ is a small positive number that is added on the diagonal to ensure that the resulting matrix is positive definite (not semi-definite)

the inverse transformation uses cholesky decomposition


Another approach would be to multiple to lower triangular matrix, but they'd require a positive diagonal, which is harderd to obtain see [https://en.wikipedia.org/wiki/Definite_matrix#Cholesky_decomposition](https://en.wikipedia.org/wiki/Definite_matrix#Cholesky_decomposition)

The API inspired by gpytorch constraints

In [ ]:
#| export
from fastcore.foundation import docs
from fastcore.basics import store_attr

In [ ]:
from meteo_imp.utils import *

In [ ]:
#| export
@docs
class PosDef(): 
    def __init__(self, noise=1e-5): store_attr()
    def transform(self,raw): return raw @ raw.mT + self.noise * torch.eye(raw.shape[-1], device=raw.device, dtype=raw.dtype)
    def inverse_transform(self, value): return torch.linalg.cholesky(value)
    
    _docs = {'cls_doc': "Positive Definite Constraint for PyTorch parameters",
             'transform':"transform any square matrix into a positive definite one",
             'inverse_transform': "tranform positive definite matrix into a matrix that can be back_transformed using `transform`"}

to_posdef = PosDef().transform

In [ ]:
constraint = PosDef()

posdef = constraint.transform(A)

In [ ]:
constraint.noise

1e-05

In [ ]:
A

tensor([[[0.7120, 0.4982, 0.9647],
         [0.6660, 0.1624, 0.1867],
         [0.8817, 0.1374, 0.1590]],

        [[0.3167, 0.3531, 0.2127],
         [0.9612, 0.0621, 0.5501],
         [0.0620, 0.3209, 0.0697]]])

In [ ]:
posdef

tensor([[[1.6858, 0.7352, 0.8495],
         [0.7352, 0.5048, 0.6392],
         [0.8495, 0.6392, 0.8215]],

        [[0.2703, 0.4434, 0.1478],
         [0.4434, 1.2303, 0.1179],
         [0.1478, 0.1179, 0.1117]]])

In [ ]:
show_as_row(is_posdef(torch.stack([posdef,A])), is_posdef_eigv(torch.stack([posdef,A])), is_symmetric(torch.stack([posdef,A])))

In [ ]:
test_eq(is_posdef(posdef).all(), True)

In [ ]:
constraint.inverse_transform(posdef)

tensor([[[ 1.2984,  0.0000,  0.0000],
         [ 0.5662,  0.4292,  0.0000],
         [ 0.6543,  0.6261,  0.0372]],

        [[ 0.5199,  0.0000,  0.0000],
         [ 0.8528,  0.7092,  0.0000],
         [ 0.2843, -0.1756,  0.0058]]])

In [ ]:
test_close(posdef, constraint.transform(constraint.inverse_transform(posdef)), eps=2e-5)

In [ ]:
symmetric_upto(posdef[0])

-8

In [ ]:
reset_seed()

### Fuzzer

In [ ]:
run_fuzzer = True # temporly disable for performance reasons

In [ ]:
def random_posdef(bs=10,n=100,noise=1e-5,n_range=(0,1), **kwargs):
    A = torch.rand(bs,n,n, **kwargs)  * (n_range[1]-n_range[0]) + n_range[0]
    return PosDef(noise).transform(A)

In [ ]:
# fuzzer
def fuzz_posdef(bs=10,n=100,noise=1e-5,n_range=(0,1), **kwargs):
    posdef = random_posdef(bs, n, noise, **kwargs)
    return pd.DataFrame(
        {'n': [n], 'noise': f"{noise:.0e}", 'range': str(n_range), 'n_samples': bs,
         'posdef': is_posdef(posdef).sum().item() / bs,
         'sym': is_symmetric(posdef).sum().item() / bs, 
         'posdef_eigv': is_posdef_eigv(posdef)[0].sum().item() / bs
    })

In [ ]:
fuzz_posdef()

n  noise   range  n_samples  posdef  sym  posdef_eigv
0  100  1e-05  (0, 1)         10     1.0  1.0          1.0

In [ ]:
n_min, n_max = -1, 1
A = torch.rand(2,100,100)  * (n_max-n_min) + n_min

In [ ]:
is_posdef(to_posdef(A))

tensor([True, True])

In [ ]:
ma = torch.tensor([[1, 7],
                   [-3, 4]])

In [ ]:
is_posdef(to_posdef(ma))

tensor(True)

In [ ]:
fuzz_posdef(device='cuda')

KeyboardInterrupt: 

In [ ]:
# %time fuzz_posdef(bs=100, device='cuda')

In [ ]:
rate_posdef = pd.concat([fuzz_posdef(n=n, noise=noise, bs=100, n_range=n_range, device='cuda') 
               for n in [10, 100]
               for noise in [1e-2, 1e-5, 1e-7]
               for n_range in [(-1,1),(0,1)]])

In [ ]:
import altair as alt
from altair import datum

In [ ]:
rate_posdef.head()

In [ ]:
def _plot_var(df, var, x='n:N', row='range', column='noise:N', y_domain=(0,1), height=70, width=50):
    bar = alt.Chart(df).mark_bar().encode(
        x = alt.X('n:N'),
        y = alt.Y(var, scale=alt.Scale(domain=y_domain)),
        color = 'n:N',
    ).properties(height=height, width=width, ) 
    
    text = alt.Chart(df).mark_text(dy=10, color='white').encode(
        x = alt.X('n:N'),
        y = alt.Y(var),
        text = alt.Text(var, format=".2f")
    )
    
    return (bar + text).facet(
        column=column,
        row=row).properties(title=var, )
    

In [ ]:
def _plot_var_box(df, var, x='n:N', row='range', column='noise:N', height=70, width=50, title=''):
    box = alt.Chart(df).mark_boxplot().encode(
        x = alt.X(x),
        y = alt.Y(var),
        color = x,
    ).properties(height=height, width=width) 

    # text = alt.Chart(df).mark_text(dy=10, color='white').encode(
    #     x = alt.X('n:N'),
    #     y = alt.Y(var),
    #     text = alt.Text(var, format=".2f")
    # )
    
    return (box).facet(
        column=column,
        row=row).properties(title=title)


In [ ]:
from IPython import display
import vl_convert as vlc
from functools import partial

#### Generation of Random positive definite matrices 

In [ ]:
def plot_posdef_simulation(n_s, noise_s, range_s, bs=100, **kwargs):
    if not run_fuzzer: return
    rate_posdef = pd.concat([fuzz_posdef(n=n, noise=noise, bs=bs, n_range=range, device='cuda', **kwargs) 
               for n in n_s for noise in noise_s for range in range_s])
    
    vl_spec = alt.hconcat(*[_plot_var(rate_posdef, var) for var in ['posdef', 'posdef_eigv']]).to_json()
    # workaround for bug in vegalite see https://github.com/altair-viz/altair/issues/2742
    svg = vlc.vegalite_to_svg(vl_spec, vl_version='v5.3')
    display.display(display.HTML(svg))

In [ ]:
plot_posdef_simulation(n_s = [10, 100], noise_s = [1e-2, 1e-5, 1e-7], range_s = [(-1, 1)], bs=1000)

Let's go big by using a matrix `1000x1000`

In [ ]:
plot_posdef_simulation(n_s = [1000], noise_s = [1e-3, 1e-4, 1e-5], range_s = [(-.1, 1)], bs=100)

for a standard noise on the diagonal less than half of the random matrices that are 1000 in size are positive definite.

Let's have a look at one of such matrices

In [ ]:
posdef = random_posdef(100, 1000)
not_pd = posdef[torch.argwhere(~is_posdef_eigv(posdef)[0])[0]]

This should be positive definite but actually it's not ...

In [ ]:
not_pd

trying with `float64` (for memory constraint on the GPU only using a `700x700` matrix)

In [ ]:
plot_posdef_simulation(n_s = [700], noise_s = [1e-3, 1e-4, 1e-5], range_s = [(-.1, 1)], bs=100)

In [ ]:
plot_posdef_simulation(n_s = [700], noise_s = [1e-4, 1e-5], range_s = [(-.1, 1)], bs=100, dtype=torch.float64)

All matrices now are positive definite

#### Multiplication

check is multiplication of matrices is not breaking the positive definite constraint

If $A$ and $B$ are both positive definite matrices $ABA$ is also positive definite
[https://en.wikipedia.org/wiki/Definite_matrix#Multiplication](https://en.wikipedia.org/wiki/Definite_matrix#Multiplication)

In [ ]:
def fuzz_op(op, # operation that takes 2 pos def matrices and return one pos def matrix
            fn_check = is_posdef,
                  n=100, # size of matrix
                  max_t=1000, # number of multiplications
                  noise=1e-5, # noise to add on diagonal
                  bs=10, # batch size
                  n_range=(0,1), # range of random numbers
                  **kwargs):
    pd1 = random_posdef(bs, n, noise, n_range, **kwargs)
    pd2 = random_posdef(bs, n, noise, n_range,**kwargs)
    stop_times = torch.zeros(bs, **kwargs)
    
    for t in torch.arange(max_t):
        pd1 = op(pd1, pd2)
        check = fn_check(pd1)
        stop_times[torch.logical_and(stop_times == 0, ~check)] = t
        if not check.any(): break
         
    stop_times[stop_times == 0] = t
    return pd.DataFrame(
        {'n': [n], 'noise': f"{noise:.0e}", 'range': str(n_range), 'n_samples': bs, 'last_t': t.item(),
         'mean_stop': stop_times.mean().item(),
         'std_stop': stop_times.std().item(),
         'stop_times': [stop_times.cpu().numpy()]})

In [ ]:
fuzz_multiply = partial(fuzz_op, lambda pd1, pd2: pd2 @ pd1 @ pd2)
fuzz_multiply_eigv = partial(fuzz_multiply, fn_check = lambda pd1: is_posdef_eigv(pd1)[0])

In [ ]:
def plot_multiply_simulation(n_s, noise_s, max_mult=1000, bs=100, **kwargs):
    mult = pd.concat([fuzz_multiply(n=n, noise=noise, bs=bs, device='cuda', **kwargs) 
               for n in n_s for noise in noise_s]).explode('stop_times')
    
    mult_eigv = pd.concat([fuzz_multiply(n=n, noise=noise, bs=bs, device='cuda', **kwargs) 
               for n in n_s for noise in noise_s]).explode('stop_times')
    
    vl_spec = alt.hconcat(*[_plot_var_box(df, 'stop_times') for df in [mult, mult_eigv]]).to_json()
    # workaround for bug in vegalite see https://github.com/altair-viz/altair/issues/2742
    svg = vlc.vegalite_to_svg(vl_spec, vl_version='v5.3')
    display.display(display.HTML(svg))
    return (mult, mult_eigv)

In [ ]:
plot_multiply_simulation(n_s=[2,3,10, 100], noise_s=[1e-3, 1e-4, 1e-5], bs=100);

#### Addition

check is multiplication of matrices is not breaking the positive definite constraint

If $A$ and $B$ are both positive definite matrices $A+B$ is also positive definite
[https://en.wikipedia.org/wiki/Definite_matrix#Addition](https://en.wikipedia.org/wiki/Definite_matrix#Addition)

In [ ]:
pd1 = random_posdef(10, 100)
pd2 = random_posdef(10, 100)

In [ ]:
is_posdef(pd1 + pd2).all()

In [ ]:
fuzz_add = partial(fuzz_op, lambda pd1, pd2: pd1 + pd2)

In [ ]:
%time fuzz_add(max_t=1e5, device='cuda')

In [ ]:
def plot_add_simulation(n_s, noise_s, max_ts=[1000], bs=100, **kwargs):
    add = pd.concat([fuzz_add(n=n, noise=noise, bs=bs, max_t=max_t, device='cuda', **kwargs) 
               for n in n_s for noise in noise_s for max_t in max_ts]).explode('stop_times')
    
    vl_spec = _plot_var_box(add, var='stop_times', height=150, width=150).to_json()

    svg = vlc.vegalite_to_svg(vl_spec, vl_version='v5.3')
    display.display(display.HTML(svg))

In [ ]:
cache_disk("add_plot")(lambda: plot_add_simulation(n_s=[50, 100, 150], noise_s=[1e-3, 1e-4, 1e-5], bs=100, max_ts=[1e5]))()

#### Numpy posdef

In [ ]:
import numpy as np

In [ ]:
arr = np.random.rand(2,3,3)

In [ ]:
arr.shape

In [ ]:
arr.transpose(0,2,1) == np.moveaxis(arr, -1, -2)

In [ ]:
def to_posdef_np(x, noise=1e-5):
    return x @ np.moveaxis(x, -1, -2) + (noise * np.eye(x.shape[-1], dtype=arr.dtype))

In [ ]:
to_posdef_np(arr)

In [ ]:
# fuzzer
def fuzz_posdef_np(n=100, noise=1e-5, bs=10, range=(0,1), dtype=np.float32):
    A = np.random.rand(bs,n,n).astype(dtype)  * (range[1]-range[0]) + range[0]
    posdef = torch.from_numpy(to_posdef_np(A, noise))
    return pd.DataFrame(
        {'n': [n], 'noise': f"{noise:.0e}", 'range': str(range), 'n_samples': bs,
         'posdef': is_posdef(posdef).sum().item() / bs,
         'sym': is_symmetric(posdef).sum().item() / bs, 
         'posdef_eigv': is_posdef_eigv(posdef)[0].sum().item() / bs
    })

In [ ]:
fuzz_posdef_np(n=1000, dtype=np.float32)

### Checker Positive Definite

This is to help finding matrices that aren't positive definite and debug the issues.
Returns a detailed dataframe row with info about the matrix and optionally logs everything to a global object

In [ ]:
#| export
from warnings import warn
from fastcore.basics import store_attr

In [ ]:
#| export
class CheckPosDef():
    def __init__(self,
                do_check:bool = False, # set to True to actually check matrix
                use_log:bool = True, # keep internal log
                warning:bool = True, # show a warning if a matrix is not pos def 
                ):
        store_attr()
        self.log = pd.DataFrame()
        self.extra_args = {}
    def add_args(self, **kwargs):
        """Add an extra argument to the next call of check_posdef """
        self.extra_args = {**kwargs, **self.extra_args}
        return self
    
    def check(self,
              x: Tensor, # (batch of) square matrix
              **extra_args
             ) -> pd.DataFrame:
        
        if not self.do_check: return
        
        self.add_args(**extra_args)
        
        x = x if x.dim() > 2 else [x]
        infos = pd.concat([*map(self._check_matrix, x, range(len(x)))])
        
        if self.use_log: self.log = pd.concat([self.log, infos])
        if self.warning and (~infos['is_pd_eigv'].all() or ~infos['is_pd_chol'].all()):
             warn("Matrix is not positive definite")
        
        self.extra_args = {} 
        return infos
    
    def _check_matrix(self,
                     x: Tensor, # square matrix
                     batch_n = 0,
                    ) -> pd.DataFrame:
        
        x = x.detach().clone() # ensure that there is a copy
        sym_upto = symmetric_upto(x)

        is_pd_eigv, eigv = is_posdef_eigv(x)
        is_pd_chol = torch.linalg.cholesky_ex(x).info.eq(0).all().item() # skip pytorch too strict symmetry check
        is_sym = is_symmetric(x).item()

        info = pd.DataFrame({
            'is_pd_eigv': is_pd_eigv.item(),
            'is_pd_chol': is_pd_chol,
            'is_sym': is_sym,
            'sym_upto': sym_upto,
            'eigv': [eigv.cpu().numpy()],
            'matrix': [x.cpu().numpy()],
            'batch_n': batch_n,
            **self.extra_args
        })

        return info

In [ ]:
CheckPosDef(True).check(A)

/tmp/ipykernel_29407/53702758.py:30: UserWarning: Matrix is not positive definite
  warn("Matrix is not positive definite")


is_pd_eigv  is_pd_chol  is_sym                                   eigv  \
0       False       False   False  [-0.62389994, 0.029978056, 1.6272488]   
0       False       False   False    [-0.8267139, 0.05724566, 1.2180507]   

                                              matrix  
0  [[0.7119788, 0.49824256, 0.964695], [0.6660003...  
0  [[0.3167084, 0.3531289, 0.21273518], [0.961167...

In [ ]:
CheckPosDef(True).check(A[0])

/tmp/ipykernel_29407/53702758.py:30: UserWarning: Matrix is not positive definite
  warn("Matrix is not positive definite")


is_pd_eigv  is_pd_chol  is_sym                                   eigv  \
0       False       False   False  [-0.62389994, 0.029978056, 1.6272488]   

                                              matrix  
0  [[0.7119788, 0.49824256, 0.964695], [0.6660003...

In [ ]:
checker = CheckPosDef(True)

checker.check(A, my_arg="my arg") # this will be another col in the log

/tmp/ipykernel_29407/53702758.py:30: UserWarning: Matrix is not positive definite
  warn("Matrix is not positive definite")


is_pd_eigv  is_pd_chol  is_sym                                   eigv  \
0       False       False   False  [-0.62389994, 0.029978056, 1.6272488]   
0       False       False   False    [-0.8267139, 0.05724566, 1.2180507]   

                                              matrix  my_arg  
0  [[0.7119788, 0.49824256, 0.964695], [0.6660003...  my arg  
0  [[0.3167084, 0.3531289, 0.21273518], [0.961167...  my arg

In [ ]:
checker.log

is_pd_eigv  is_pd_chol  is_sym                                   eigv  \
0       False       False   False  [-0.62389994, 0.029978056, 1.6272488]   
0       False       False   False    [-0.8267139, 0.05724566, 1.2180507]   

                                              matrix  my_arg  
0  [[0.7119788, 0.49824256, 0.964695], [0.6660003...  my arg  
0  [[0.3167084, 0.3531289, 0.21273518], [0.961167...  my arg

In [ ]:
checker.add_args(show="only once")
checker.check(posdef)
checker.check(A)
checker.log

/tmp/ipykernel_29407/53702758.py:30: UserWarning: Matrix is not positive definite
  warn("Matrix is not positive definite")


is_pd_eigv  is_pd_chol  is_sym                                    eigv  \
0       False       False   False   [-0.62389994, 0.029978056, 1.6272488]   
0       False       False   False     [-0.8267139, 0.05724566, 1.2180507]   
0        True        True    True  [0.00043795342, 0.37046388, 2.6411798]   
0        True        True    True  [1.6886237e-05, 0.18801452, 1.4242249]   
0       False       False   False   [-0.62389994, 0.029978056, 1.6272488]   
0       False       False   False     [-0.8267139, 0.05724566, 1.2180507]   

                                              matrix  my_arg       show  
0  [[0.7119788, 0.49824256, 0.964695], [0.6660003...  my arg        NaN  
0  [[0.3167084, 0.3531289, 0.21273518], [0.961167...  my arg        NaN  
0  [[1.6858058, 0.73517776, 0.8495334], [0.735177...     NaN  only once  
0  [[0.2702705, 0.44336805, 0.14780542], [0.44336...     NaN  only once  
0  [[0.7119788, 0.49824256, 0.964695], [0.6660003...     NaN        NaN  
0  [[0.3167084, 0.3531289, 0.21273518], [0.961167...     NaN        NaN

In [ ]:
B = torch.rand(2,3,3) # a batch of matrices

In [ ]:
is_symmetric(B).shape

torch.Size([2])

In [ ]:
checker.check(B)

/tmp/ipykernel_29407/53702758.py:30: UserWarning: Matrix is not positive definite
  warn("Matrix is not positive definite")


is_pd_eigv  is_pd_chol  is_sym                                    eigv  \
0       False       False   False  [-0.30987626, -0.012034075, 1.2929032]   
0       False       False   False   [-0.32521826, -0.022067621, 1.461368]   

                                              matrix  
0  [[0.6150076, 0.7986615, 0.5860322], [0.3124973...  
0  [[0.3013246, 0.8972247, 0.42320126], [0.572971...

In [ ]:
test_close(B[0] @ A, (B @ A)[0]) # example batched matrix multiplication

### Diagonal Positive Definite Contraint

this is a simpler contraint that make the matrix diagonal and positive definite, by forcing it to have positive numbers on the diagonal.

given a random vector $a$ it is transformed into a diagonal positive definite matrix using:

$A_{diag\ pos\ def} = e^a I$

the inverse transformation is the log of the diagonal

In [ ]:
#| export
@docs
class DiagPosDef(): 
    def transform(self,raw): return torch.diag(torch.exp(raw))
    def inverse_transform(self, value): return torch.log(torch.diag(value))
    
    _docs = {'cls_doc': "Diagonal Positive Definite Constraint for PyTorch parameters",
             'transform':"transform any vector into a diagonal positive definite matrix",
             'inverse_transform': "tranform diagonal positive definite matrix into a vector that can be back transformed using `transform`"}

to_diagposdef = DiagPosDef().transform

In [ ]:
dpd_const = DiagPosDef()
a = torch.rand(3)

In [ ]:
dpd_const.transform(a)

tensor([[1.1899, 0.0000, 0.0000],
        [0.0000, 2.0571, 0.0000],
        [0.0000, 0.0000, 1.4777]])

In [ ]:
test_close(a, dpd_const.inverse_transform(dpd_const.transform(a)))

## Conditional Predictions

Therefore we need to compute the conditional distribution of a normal ^[https://cs.nyu.edu/~roweis/notes/gaussid.pdf eq, 5a, 5d]

$$ X = \left[\begin{array}{c} x \\ o \end{array} \right] $$

$$ p(X) = N\left(\left[ \begin{array}{c} \mu_x \\ \mu_o \end{array} \right], \left[\begin{array}{cc} \Sigma_{xx} & \Sigma_{xo} \\ \Sigma_{ox} & \Sigma_{oo} \end{array} \right]\right)$$

where $x$ is a vector of variable that need to predicted and $o$ is a vector of the variables that have been observed


then the conditional distribution is:

$$p(x|o) = N(\mu_x + \Sigma_{xo}\Sigma_{oo}^{-1}(o - \mu_o), \Sigma_{xx} - \Sigma_{xo}\Sigma_{oo}^{-1}\Sigma_{ox})$$

In [ ]:
#| export
import torch
from torch.distributions import MultivariateNormal
from torch.linalg import cholesky
from torch import cholesky_inverse
from torch import Tensor

from fastcore.test import *
from meteo_imp.utils import *
from typing import List

In [ ]:
#| export
def conditional_guassian(
                         μ: Tensor, # mean with shape `[n_vars]`
                         Σ: Tensor, # cov with shape `[n_vars, n_vars] `
                         obs: Tensor, # Observations with shape `[n_obs]`, where `n_obs = sum(idx)`
                         mask: Tensor # Boolean tensor specifying for each variable is observed (True) or not (False). Shape `[n_vars]`
                        ) -> ListMNormal: # Distribution conditioned on observations. shape `[n_vars - n_obs]`
    assert μ.shape[0] == mask.shape[0]
    assert obs.shape[0] == sum(mask)
    
    μ_x = μ[~mask]
    μ_o = μ[mask]
    # the double square brackets `:][:` are needed to keep the dimensionality even for empty tensors 
    Σ_xx = Σ[~mask,:][:, ~mask]
    Σ_xo = Σ[~mask,:][:,  mask]
    Σ_ox = Σ[ mask,:][:, ~mask]
    Σ_oo = Σ[ mask,:][:,  mask]
    
    Σ_oo_inv = torch.inverse(Σ_oo) # cholesky_inverse(cholesky(Σ_oo))
    
    
    mean = μ_x + Σ_xo@Σ_oo_inv@(obs - μ_o)
    cov = Σ_xx - Σ_xo@Σ_oo_inv@Σ_ox
    
    return ListMNormal(mean, cov)
    

In [ ]:
# example distribution with only 2 variables
μ = torch.tensor([.5, 1.])
Σ = torch.tensor([[1., .5], [.5 ,1.]])


mask = torch.tensor([True, False]) # second variable is the observed one

obs = torch.tensor([5.]) # value of second variable

gauss_cond = conditional_guassian(μ, Σ, obs, mask)

# hardcoded values to test that the code is working, see also for alternative implementation https://python.quantecon.org/multivariate_normal.html
test_close(3.25, gauss_cond.mean.item())
test_close(.75, gauss_cond.cov.item())

### Batches

cannot have proper batch support, or at least not in a straigthforward way as the shape of the output would be different for the different batches.

so using a for-loop to temporarly fix the situation

In [ ]:
#| export
def cond_gaussian_batched(dist: ListMNormal,
                         obs, # this needs to have the same shape of the mask !!! 
                         mask
                         ) -> List[ListMNormal]: # lists of distributions for element in the batch
    return [conditional_guassian(dist.mean[i], dist.cov[i], obs[i][mask[i]], mask[i]) for i in range(obs.shape[0])]
        

In [ ]:
reset_seed(10)
mean = torch.rand(2,3) # batch
cov = to_posdef(torch.rand(2,3,3))
mask = torch.rand(2,3) > .3
obs = torch.rand(2,3)

In [ ]:
conditional_gaussian_batched(mean, cov, obs, mask)

In [ ]:
mask.shape, obs.shape

In [ ]:
assert mean.shape == mask.shape
assert mean.dim() == 2

In [ ]:
obs.shape

In [ ]:
mean_x = mean[~mask]
mean_o = mean[mask]

In [ ]:
mask

In [ ]:
mean_x

In [ ]:
cov.shape

In [ ]:
cov[~mask]

In [ ]:
cov

In [ ]:
cov[0][~mask[0], ~mask[0]]

In [ ]:
cov[0][mask[0],:][:, mask[0]].shape

### Performance

analysis of the performance of inverting a positive definite matrix

Use `cholesky` decomposition and `cholesky_solve` to improve performance of matrix inversion

see the [Probabilist machine learning course from uni Tübigen](https://uni-tuebingen.de/en/180804), specifically the code from the [Gaussian Regression Notebook](https://uni-tuebingen.de/fileadmin/Uni_Tuebingen/Fakultaeten/MatNat/Fachbereiche/Informatik/Lehrstuehle/MethMaschLern/Probabilistic_ML/Notebook_Vorlesung_7___9/Gaussian_Linear_Regression.ipynb) for details

This is the direct implementation of the equations

In [ ]:
def _conditional_guassian_base(
                         μ: Tensor, # mean with shape `[n_vars]`
                         Σ: Tensor, # cov with shape `[n_vars, n_vars] `
                         obs: Tensor, # Observations with shape `[n_vars]`
                         idx: Tensor # Boolean tensor specifying for each variable is observed (True) or not (False). Shape `[n_vars]`
                        ) -> ListNormal: # Distribution conditioned on observations
    μ_x = μ[~idx]
    μ_o = μ[idx]
    
    Σ_xx = Σ[~idx,:][:, ~idx]
    Σ_xo = Σ[~idx,:][:, idx]
    Σ_ox = Σ[idx,:][:, ~idx]
    Σ_oo = Σ[idx,:][:, idx]
    
    Σ_oo_inv = torch.linalg.inv(Σ_oo)
    
    mean = μ_x + Σ_xo@Σ_oo_inv@(obs - μ_o)
    cov = Σ_xx - Σ_xo@Σ_oo_inv@Σ_ox
    
    return ListNormal(mean, cov)
    

 faster version

In [ ]:
n_var = 5
mean = torch.rand(n_var, dtype=torch.float64)
cov = to_posdef(torch.rand(n_var, n_var, dtype=torch.float64))
dist = MultivariateNormal(mean, cov)
idx = torch.rand(n_var, dtype=torch.float64) > .5
obs = torch.rand(n_var, dtype=torch.float64)[idx]

In [ ]:
torch.linalg.inv(cov) 

In [ ]:
(torch.linalg.inv(cov) - cholesky_inverse(torch.linalg.cholesky(cov))).max()

In [ ]:
test_close(torch.linalg.inv(cov), cholesky_inverse(torch.linalg.cholesky(cov)), eps=1e-2)

In [ ]:
reset_seed()
A = to_posdef(torch.rand(1000, 1000, dtype=torch.float64)) + torch.eye(1000) * 1e-3 # noise to ensure is positive definite

In [ ]:
is_symmetric(A)

In [ ]:
is_posdef(A)

In [ ]:
%timeit torch.linalg.inv(A)

In [ ]:
%timeit cholesky_inverse(torch.linalg.cholesky(A))

The second version is way faster

In [ ]:
test_close(conditional_guassian(mean, cov, obs, idx).mean, _conditional_guassian_base(mean, cov, obs, idx).mean)

In [ ]:
B = to_posdef(torch.rand(n_var, n_var, dtype=torch.float64))

In [ ]:
B @ torch.inverse(cov)

In [ ]:
torch.cholesky_solve(cholesky(cov), B)

## Helper

### cov2std

In [ ]:
x = torch.stack([torch.eye(3)*i for i in  range(1,4)])

In [ ]:
x

In [ ]:
torch.diagonal(x, dim1=1, dim2=2)

In [ ]:
#| export
def cov2std(x):
    "convert cov of array of covariances to array of stddev"
    return torch.sqrt(torch.diagonal(x, dim1=-2, dim2=-1))

## Export

In [ ]:
#| hide
from nbdev import nbdev_export
nbdev_export()